import "@/app/globals.css";
import NavBar from "@/components/NavBar";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
const roboto = Roboto({ preload: true, weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "RAWR",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="night">
      <body className={`${roboto.className} px-[20.5rem] pt-8`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
