import "@/app/globals.css";
import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar";
import type { GetServerSidePropsContext, Metadata } from "next";
import { Roboto } from "next/font/google";
import { cookies } from "next/headers";

const roboto = Roboto({ preload: true, weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "RAWR",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const theme = cookies().get("theme");

  return (
    <html lang="en" data-theme={theme?.value}>
      <body
        className={`${roboto.className} 2xl:px-[20.5rem] xl:px-[5rem] md:px-[2rem] pt-2 lg:pt-8`}
      >
        <NavBar theme={theme?.value} />
        {children}
      </body>
    </html>
  );
}
